bestemmingen = ['Ter Apel', "'s-Hertogenbosch", 'Appelscha','Cochem','Gasselterboerveenschemond']
print (bestemmingen)
print sorted(bestemmingen)
print (bestemmingen)
sorted(bestemmingen, reverse = True)
print(bestemmingen)
bestemmingen.reverse()
print(bestemmingen)
bestemmingen.reverse()
print(bestemmingen)
bestemmingen.sort()
print(bestemmingen)
bestemmingen.sort(reverse=True)
print(bestemmingen)
